GEDGO_ALLOW_FILE_UPLOADS = True
GEDGO_SENDFILE_HEADER = 'X-Accel-Redirect'
GEDGO_SENDFILE_PREFIX = '/protected/'
GEDGO_SITE_TITLE = 'My Genealogy Site'
GEDGO_REDIS_SERVER = 'redis'
GEDGO_RESEARCH_FILE_STORAGE = 'gedgo.storages.FileSystemSearchableStorage'
GEDGO_RESEARCH_FILE_ROOT = 'media/'
GEDGO_DOCUMENTARY_STORAGE = 'gedgo.storages.FileSystemSearchableStorage'
GEDGO_DOCUMENTARY_ROOT = 'media/'
GEDGO_GEDCOM_FILE_STORAGE = 'gedgo.storages.FileSystemSearchableStorage'
GEDGO_GEDCOM_FILE_ROOT = 'media/'
GEDGO_SHOW_RESEARCH_FILES = True
